DECLARE
  REGION REGIONS.REGION_NAME%TYPE:='&REGION';
  COUNTRY_COUNT NUMBER:=0;

BEGIN
  
  CASE UPPER(REGION)
    WHEN 'EUROPE' THEN
      
      SELECT COUNT(*) 
      INTO  COUNTRY_COUNT
      FROM COUNTRIES
      WHERE REGION_ID=1;
      DBMS_OUTPUT.PUT_LINE('EUROPE '||COUNTRY_COUNT||' '||'COUNTRIES');
   
    WHEN 'AMERICAS' THEN
    
    SELECT COUNT(*)
    INTO COUNTRY_COUNT
    FROM COUNTRIES
    WHERE REGION_ID=2;
    DBMS_OUTPUT.PUT_LINE('AMERICAS '||COUNTRY_COUNT||' '||'COUNTRIES');
       
    WHEN 'ASIA' THEN
    SELECT COUNT(*)
    INTO COUNTRY_COUNT
    FROM COUNTRIES
    WHERE REGION_ID=3;
    DBMS_OUTPUT.PUT_LINE('ASIA '||COUNTRY_COUNT||' '||'COUNTRIES');
       
    ELSE 
      DBMS_OUTPUT.PUT_LINE('NO REGION WITH NAME');
  
  END CASE;
  
  
  
END;
/