DECLARE

  BILL_AMOUNT NUMBER;
  bill_amount_string VARCHAR2(30);
BEGIN
  BILL_AMOUNT:=1000;
  BILL_AMOUNT_STRING:=TO_CHAR(BILL_AMOUNT,'$999999999,999.00');
  
  DBMS_OUTPUT.PUT_LINE(BILL_AMOUNT_STRING);
END;
/



