BEGIN
DBMS_SCHEDULER.CREATE_JOB(
        JOB_NAME=>'MYKJOB',
        JOB_TYPE=>'STORED_PROCEDURE',
        JOB_ACTION=>'SCHEDULER_PROCEDURE',
        ENABLED=>TRUE,
        REPEAT_INTERVAL=>'FREQ=MINUTELY;INTERVAL=1;BYSECOND=25'); -- WILL RUN EVERY MINUTE AT 25'TH SECOND
END;