--1)CREATE A MATERIALIZED VIEW , (USER MUST HAVE CREATE MATERIALIZED VIEW GRANT)
--CREATE MATERIALIZED VIEW EMP_MAT_VIEW 
--AS SELECT FIRST_NAME,LAST_NAME , SALARY 
--FROM EMPLOYEES

--2)SEE THE SAME RESULTS
--SELECT SUM(SALARY) FROM EMP_MAT_VIEW
--select sum(salary) from employees

--3)CHANGE SALARY IN EMPLOYEES TABLE
UPDATE EMPLOYEES 
  SET SALARY=SALARY-100;

--4)LOOK ON A DIFFERENCE
--SELECT SUM(SALARY) FROM EMP_MAT_VIEW
--select sum(salary) from employees
  
----5) REFRESH MATERIALIZED VIEW (WE CAN DO IT IN SHCEDULER)
----DBMS_REFRESH.REFRESH - REFRESH THE VIEW
----DBMS_REFRESH.MAKE - AUTOMATE THIS TASK  CREATE THE LIST OF VIEWS TO REFRESH , AND REFRESH IT IN SOME INTERVAL(LOOK DETAILS AND 238 PAGE IN PL/SQL RECIPES)
 
  --MAKE A LIST(GROUP) OF MATERIALIZED VIEWS (ONLY ONCE) we can set date and  interval but i set null null in this arguments
 -- EXEC DBMS_REFRESH.MAKE('HR_MVs','EMP_MAT_VIEW',NULL,NULL) 
  
  --REFRESH GROUP
-- EXEC DBMS_REFRESH.REFRESH('HR_MVs')

--6)SEE THE SAME RESULT , BECAUSE WE REFRESH MATERIALIZED VIEW
--SELECT SUM(SALARY) FROM EMP_MAT_VIEW
--select sum(salary) from employees