DECLARE 
CURSOR  EMP_CURSOR IS
SELECT FIRST_NAME,LAST_NAME,EMAIL 
FROM EMPLOYEES
WHERE EMPLOYEE_ID=&EMP_ID;

FIRST VARCHAR2(20);
LAST VARCHAR2(25);
EMAIL VARCHAR2(25);

BEGIN

OPEN emp_cursor;
FETCH emp_cursor into first,last,email;

IF EMP_CURSOR%NOTFOUND THEN
  RAISE NO_DATA_FOUND;
  
  ELSE
  
    FETCH EMP_CURSOR INTO FIRST,LAST,EMAIL;
    IF EMP_CURSOR%FOUND THEN
        RAISE TOO_MANY_ROWS;  
     ELSE
      DBMS_OUTPUT.PUT_LINE(FIRST||' ' ||LAST);
   END IF;  
END IF;
  
END;
/