DECLARE
CURSOR EMP_CUR IS
SELECT * FROM EMPLOYEES
WHERE employee_id=&emp_id;

emp_rec EMPLOYEES%rowtype;
BEGIN

OPEN emp_cur;

FETCH emp_cur INTO emp_rec;

IF EMP_CUR%FOUND THEN
  DBMS_OUTPUT.PUT_LINE('INFO '||EMP_REC.FIRST_NAME||' '||EMP_REC.LAST_NAME);
  ELSE
    DBMS_OUTPUT.PUT_LINE('! NO DATA');
  END IF;

CLOSE emp_cur;

EXCEPTION
WHEN NO_DATA_FOUND THEN
   DBMS_OUTPUT.PUT_LINE('! NO DATA');
END;
/