DECLARE
TYPE EMP_INFO IS RECORD(FIRST EMPLOYEES.FIRST_NAME%TYPE,
                        LAST EMPLOYEES.LAST_NAME%TYPE,
                        EMAI EMPLOYEES.EMAIL%TYPE);

emp_info_rec EMP_INFO;
BEGIN
  SELECT FIRST_NAME,LAST_NAME ,EMAIL INTO EMP_INFO_REC
  FROM EMPLOYEES
  WHERE LAST_NAME='Seo';
  
  DBMS_OUTPUT.PUT_LINE('INFO = '||EMP_INFO_REC.LAST||' '||EMP_INFO_REC.FIRST);
  
END;
/