DECLARE
  TYPE num_type IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
  
  NUMS NUM_TYPE;
BEGIN
  NULL;
  NUMS(1):=10.10;
  NUMS(2):=10.23;
  NUMS(3):=1.45;
  
  DBMS_OUTPUT.PUT_LINE(NUMS.COUNT);
  
  FOR I IN 1..NUMS.COUNT LOOP
    DBMS_OUTPUT.PUT_LINE(NUMS(I));
  END LOOP;
END;