--CREATE OR REPLACE PACKAGE empDATA AS
--TYPE emps_type IS TABLE OF employees%ROWTYPE INDEX BY BINARY_INTEGER;
--FUNCTION GET_EMP_DATA RETURN EMPS_TYPE;
--END ;

CREATE OR REPLACE PACKAGE BODY EMPDATA AS
  FUNCTION GET_EMP_DATA RETURN EMPS_TYPE IS 
    CURSOR DRIVER IS 
    SELECT * FROM EMPLOYEES
    ORDER BY LAST_NAME,FIRST_NAME;
    RECS EMPS_TYPE;
  BEGIN
    OPEN DRIVER;
    FETCH DRIVER BULK COLLECT INTO RECS;
    CLOSE DRIVER;
    RETURN RECS;
  END;
END;