CREATE OR REPLACE JAVA SOURCE NAMED "Employees" AS
...
  SOURCE
...

--AND NOW COMPILE CODE
ALTER JAVA CLASS "Employees" RESOLVE

--ANOTHER METHOD TO LOAD .JAVA FILE
LOADJAVA -USER DBUSER Employees.java