DECLARE

EMP_ID NUMBER:=&EMP_ID;
EMP_REC EMPLOYEES%ROWTYPE;
BEGIN
  NULL;
  SELECT * INTO EMP_REC FROM EMPLOYEES 
  WHERE EMPLOYEE_ID=EMP_ID;
  
  RAISE INVALID_CURSOR;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('NO DATA ');
  WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('OTHERS');
END;
/