-- TESTING FUNCTION
--EXEC INCREASE_WAGE(198,0.5,100000);

CREATE OR REPLACE PROCEDURE INCREASE_WAGE(EMPNO IN NUMBER,
                                          PCT_INCREASE IN NUMBER,
                                          UPPER_BOUND IN NUMBER)AS
  
EMP_COUNT NUMBER:=0;
emp_sal EMPLOYEES.SALARY%TYPE;

RESULTS VARCHAR2(50);
BEGIN

  SELECT SALARY
  INTO EMP_SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID=EMPNO;
  
  IF EMP_SAL<UPPER_BOUND AND
      ROUND(EMP_SAL+ EMP_SAL*PCT_INCREASE,2 )<UPPER_BOUND THEN
      
      UPDATE EMPLOYEES 
      SET SALARY=ROUND(EMP_SAL+ EMP_SAL*PCT_INCREASE,2 )
      WHERE EMPLOYEE_ID=EMPNO;
      
      RESULTS:='SUCCESSFUL INCREASE';
      ELSE
      RESULTS:='TO MUCH';
      END IF;
  
    DBMS_OUTPUT.PUT_LINE(RESULTS);
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('N/A');
END;