CREATE OR REPLACE TRIGGER TEMP_DATE_ADD_1_YEAR 
  before UPDATE OF HIRE_DATE ON TEMP
FOR EACH ROW
DECLARE 
--  CURSOR temp_cur IS 
--  SELECT *
--  FROM TEMP 
--  WHERE HIRE_DATE=:NEW.HIRE_DATE
--    FOR UPDATE;
BEGIN
--  FOR TEMP_REC IN TEMP_CUR LOOP
--    UPDATE TEMP 
--    SET HIRE_DATE= :NEW.HIRE_DATE
--    WHERE CURRENT OF TEMP_CUR;
--  END LOOP;
    :new.hire_date:=sysdate-10;
  NULL;
END;

