CREATE OR REPLACE TRIGGER CHECK_EMAIL_ADDRESS
BEFORE INSERT OR UPDATE ON TEMP
FOR EACH ROW
DECLARE
BEGIN
  IF NOT INSTR(:NEW.EMAIL,'@')>0 THEN
    RAISE_APPLICATION_ERROR(-20001,'INVALID EMAIL');
  END IF;
END;
/