CREATE OR REPLACE TRIGGER LOGIN_AUDIT_EVENT
AFTER LOGON ON DATABASE
DECLARE
BEGIN
  INSERT INTO LOGIN_AUDIT_TABLE
  VALUES(HR.LOGIN_AUDIT_SEQ.NEXTVAL,
          SYSDATE,
          SYS_CONTEXT('USERENV','SESSION_USERID'),
          SYS_CONTEXT('USERENV','IP_ADDRESS'));
          
  
END;
/
