DECLARE
  NEW_TIME DATE;
BEGIN
  NULL;
  SELECT SYSDATE+10/1440 INTO NEW_TIME  FROM DUAL;
 
 
  DBMS_OUTPUT.PUT_LINE(TO_CHAR( NEW_TIME,'DD-MM-YYYY HH24:MI'));  
  DBMS_OUTPUT.PUT_LINE(NUMTODSINTERVAL(10,'MINUTE'));
  
END;